# Generated by Django 4.1 on 2022-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("dob", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("mobile", models.IntegerField(max_length=10)),
                ("location", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("createdtime", models.CharField(max_length=30)),
            ],
        ),
    ]
