# Generated by Django 4.1 on 2022-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_cart_category_login_order_seller_seller_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller_product",
            name="seller_id",
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
