# Generated by Django 4.1 on 2022-08-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_seller_product_seller_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(max_length=30)),
                ("category_id", models.IntegerField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("price", models.IntegerField(max_length=30)),
                ("discount", models.IntegerField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="seller_id",
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
